### ISSUE TITLE
[Question] PSNR Experiment

### ISSUE THREAD

**Issue by jamesgzl** [nissmar/Radiance-Fields#1]
Have you ever tried the result of svox2 of your implementation with offical svox2? I try with grid size=16 and downsample lego with scale=8, however... I dont reach the result as good as offical svox2. Have u ever try it?

**Comment by nissmar** [comment]
Svox2 uses a custom cuda kernel to parallelize across rays, allowing a fast optimization with spherical harmonics of degree 9. This student project provides a simpler, slower implementation without spherical harmonics (in the non space-carving version) which cannot reach the PSNR mentioned by svox2. For more details, see the [full report](https://github.com/nissmar/Radiance-Fields/blob/main/Report/main.pdf).

**Comment by jamesgzl** [comment]
Thank you for reply！
I see that he metion he implement the svox2 in README. the code simpler than svox2 which is quiet nice.so i wonder if the code could satisfy the psnr as good as svox2 does😁


best wish！



发自我的iPhone


------------------ Original ------------------
From: nissmar ***@***.***&gt;
Date: Thu,May 19,2022 5:46 PM
To: nissmar/Radiance-Fields ***@***.***&gt;
Cc: JamesGZL ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [nissmar/Radiance-Fields] [Question] PSNR Experiment (Issue #1)





 
Svox2 uses a custom cuda kernel to parallelize across rays, allowing a fast optimization with spherical harmonics of degree 9. This student project provides a simpler, slower implementation without spherical harmonics (in the non space-carving version) which cannot reach the PSNR mentioned by svox2. For more details, see the full report.
